fragment Journey on Journey {
  id
  name
  avatar
  to
  lastStudyDate
  createdAt
  updatedAt
}

fragment DetailedJourney on Journey {
  ...Journey
  paths {
    ...DetailedPath
  }
}

fragment DetailedPath on UserPath {
  id
  name
  description
  isMain
  isActive
  type
  profession
}

fragment MaterialMetadata on MaterialMetadata {
  title
  description
  estimatedDuration
  focusAreas
  focusSkills
}

fragment Material on Material {
  id
  pathID
  metadata {
    ...MaterialMetadata
  }
  type
  genStatus
  compStatus
  convStatus
  feedbackStatus
  createdAt
  completedAt
  unseenAiFeedbacks
}

fragment MaterialStatusses on Material {
  genStatus
  compStatus
  convStatus
  feedbackStatus
}

fragment AIFeedbackPart on AIFeedbackPart {
  type
  text
}

fragment AIFeedbackInterface on AIFeedbackInterface {
  type
  question
  turnIndex
  parts {
    ...AIFeedbackPart
  }
}

fragment AIFeedback on AIFeedback {
  id
  createdAt
  feedback {
    ...AIFeedbackInterface
  }
  material_ID
  user_ID
  seen
}

fragment UserAnswer on UserAnswer {
  id
  createdAt
  answers
}

fragment DetailedMaterial on Material {
  ...Material
  details {
    ...MaterialDetails
  }
  answer {
    ...UserAnswer
  }
  aiFeedbacks(pagination: { limit: 1000 }) {
    items {
      ...AIFeedback
    }
  }
  turns(pagination: { limit: 1000 }) {
    items {
      ...ConversationTurn
    }
  }
}

fragment StoryPart on StoryPart {
  type
  ssml
  hasPicture
  question {
    ...QuizQuestion
  }

  audioId
  pictureId
}

fragment StoryDetails on StoryDetails {
  parts {
    ...StoryPart
  }
}

fragment QuizPreludeItem on QuizPreludeItem {
  type
  content
  hasPicture
  pictureId
  audioId
}

fragment QuizPrelude on QuizPrelude {
  id
  parts {
    ...QuizPreludeItem
  }
}

fragment QuestionItem on QuestionItem {
  id
  text
  pictureId
  hasPicture
}

fragment QuizQuestion on QuizQuestion {
  id
  type
  question
  preludeID
  choices {
    ...QuestionItem
  }
  items {
    ...QuestionItem
  }
  secondItems {
    ...QuestionItem
  }
}

fragment ConversationCharacter on ConversationCharacter {
  name
  description
  voice
  avatar
  gender
}

fragment ConversationDetails on ConversationDetails {
  instructions
  characters {
    ...ConversationCharacter
  }
}
fragment QuizDetails on QuizDetails {
  preludes {
    ...QuizPrelude
  }
  questions {
    ...QuizQuestion
  }
}

fragment MaterialDetails on MaterialDetails {
  type
  ... on StoryDetails {
    ...StoryDetails
  }

  ... on QuizDetails {
    ...QuizDetails
  }
  ... on ConversationDetails {
    ...ConversationDetails
  }
}

fragment ConversationTurn on ConversationTurn {
  id
  createdAt
  audio_ID
  character
  text
  nextTurn
}

fragment ConversationUpdate on ConversationUpdate {
  turn {
    ...ConversationTurn
  }
  nextTurn
}

fragment AnswerMaterialResponse on AnswerMaterialResponse {
  next
  newPath
  newMaterial
}

fragment UserDocExplanation on UserDocExplanation {
  type
  ui
  text
  pictureId
  audioId
}
fragment UserDocTemplate on UserDocTemplate {
  id
  title
  description
  includes
  explanations {
    ...UserDocExplanation
  }
}

fragment UserDoc on UserDoc {
  id
  createdAt
  updatedAt
  template_ID
  user_ID
  journey_ID
  template {
    ...UserDocTemplate
  }
}

fragment ModelSet on ModelSet {
  id
  name
  description
}
