query GetMyJourneys {
  user {
    my_journeys {
      items {
        ...Journey
      }
    }
  }
}

query GetJourneyDetailed($id: ID!) {
  user {
    journey(id: $id) {
      ...DetailedJourney
    }
  }
}

# query GetPath($id: ID!) {
#   user {
#     path(id: $id) {
#       ...DetailedPath
#     }
#   }
# }

query GetPathMaterials(
  $journeyId: ID!
  $pathID: String!
  $pagination: PaginationInput
) {
  user {
    path_materials(
      journeyId: $journeyId
      pathID: $pathID
      pagination: $pagination
    ) {
      items {
        ...Material
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}

query GetMaterial($id: ID!) {
  user {
    material(id: $id) {
      ...Material
    }
  }
}

query GetMaterialDetails($id: ID!) {
  user {
    material(id: $id) {
      ...DetailedMaterial
    }
  }
}

subscription StartConversation($materialId: ID!) {
  start_conversation(materialId: $materialId) {
    ...ConversationUpdate
  }
}

query GetConversationTurns($materialId: ID!) {
  user {
    conversation_turns(materialId: $materialId) {
      ...ConversationTurn
    }
  }
}

query ParsedUnits($text: String!, $journeyId: ID!) {
  user {
    parsed_units(text: $text, journeyId: $journeyId)
  }
}

query GetDocumentation($input: DocumentationInput!) {
  user {
    documentation(input: $input) {
      ...UserDoc
    }
  }
}

query GetJourneyDocs($journeyId: ID!, $pagination: PaginationInput) {
  user {
    journey_docs(journeyId: $journeyId, pagination: $pagination) {
      items {
        ...UserDoc
      }
    }
  }
}

query GetMaterialFeedbacks($materialId: ID!) {
  user {
    material_feedbacks(materialId: $materialId) {
      ...AIFeedback
    }
  }
}

query GetModelSets {
  user {
    model_sets {
      items {
        ...ModelSet
      }
    }
  }
}
